## Machine Learning Zoomcamp

#### 1.7 Introduction to NumPy
Plan:

- Creating arrays
- Multi-dimensional arrays
- randomly generated arrays
- Element-wise operations
    - Comparison Operations
    - Logical operations
- Summarizing operations

In [2]:
import numpy as np

### Creating arrays

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.full(10, 2.5) # fill the number 2.5 in the size of 10 array

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [9]:
a = np.array([1, 2, 3, 5, 7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

In [11]:
a[2] = 10
a

array([ 1,  2, 10,  5,  7, 12])

In [ ]:
np.arange(3, 10) # create 3-9 array, 10 is exclusive, similar to python func. range()

array([3, 4, 5, 6, 7, 8, 9])

In [17]:
np.linspace(0, 10, 11) # creating a array filled with the number in 0 to 10 (inclusive) with size of 11

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### Multi-dimensional arrays

In [ ]:
np.zeros((5, 2)) # 5 rows and 2 colmns filled with zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
n = np.array([
    [1, 2, 3], #0
    [4, 5, 6], #1
    [7, 8, 9], #2
])  #0 #1 #2
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
n[1][2] # not recommended

np.int64(6)

In [ ]:
n[1, 2] # recommended

np.int64(6)

In [23]:
n[2] = [1, 1, 1]
n

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

In [24]:
n[:, 2]

array([3, 6, 1])

### Randomly generated arrays

In [29]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [31]:
np.random.seed(2)
np.random.randn(5, 2) # sample from standard normal dist.
np.random.randint(low = 0, high = 100, size = (5, 2))


array([[37, 39],
       [67,  4],
       [42, 51],
       [38, 33],
       [58, 67]])

### Element-wise operations

In [32]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
a + 1 # in usual python list, this operation cannot be executed


array([0, 2, 4, 6, 8])

In [35]:
a * 2

array([0, 2, 4, 6, 8])

In [39]:
b = (10 + (a * 2)) ** 2 / 100

In [41]:
a * b

array([ 0.  ,  1.44,  3.92,  7.68, 12.96])

### Comparison Operations

In [42]:
a >= b

array([False, False,  True,  True,  True])

In [43]:
a > b

array([False, False,  True,  True,  True])

In [44]:
a[a > b]

array([2, 3, 4])

### Summarizing operations

In [45]:
a.max()

np.int64(4)

In [46]:
n.std()

np.float64(1.8257418583505538)

In [47]:
n.mean()

np.float64(2.6666666666666665)