## Linear Algebra Refresher

In [3]:
import numpy as np

### Vector operations

In [4]:
u = np.array([2, 4, 5, 6])
2 * u

array([ 4,  8, 10, 12])

In [5]:
v = np.array([1, 0, 0, 2])
u + v

array([3, 4, 5, 8])

### Multiplication

In [6]:
u * v

array([ 2,  0,  0, 12])

In [7]:
u.shape[0]

4

dot product

In [8]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    n = u.shape[0]
    result = 0.0
    for i in range(n):
        result += u[i] * v[i]
    return result

In [9]:
vector_vector_multiplication(u, v)

np.float64(14.0)

In [10]:
u.dot(v) # same as what we wrote above

np.int64(14)

Matrix - Vector Multiplication

In [14]:
U = np.array([
    [1, 2, 3, 9],
    [4, 5, 6, 12],
    [7, 8, 9, 15]
])

In [ ]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
        
    return result

In [16]:
matrix_vector_multiplication(U, v)

array([19., 28., 37.])

In [17]:
U.dot(v) # same as matrix_vector_multiplication() above, numpy knows how to deal with dimension problem

array([19, 28, 37])

Matrix - Matrix Multiplication

In [26]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0],
])

In [27]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0], "Error: dimension should be (x, y) @ (y, z), where y should be same"
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    result = np.zeros((num_rows, num_cols))
    for i in range(num_rows):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    return result
    

In [28]:
matrix_matrix_multiplication(U, V)

array([[19. , 17. ,  7. ],
       [28. , 30.5, 19. ],
       [37. , 44. , 31. ]])

In [29]:
U.dot(V) # same result as what we wrote above

array([[19. , 17. ,  7. ],
       [28. , 30.5, 19. ],
       [37. , 44. , 31. ]])

### Identity Matrix

```
[
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1],
]
```

In [30]:
I = np.eye(3)

In [31]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [32]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [35]:
I.dot(V.transpose())

array([[1. , 0. , 0. , 2. ],
       [1. , 0.5, 2. , 1. ],
       [2. , 1. , 1. , 0. ]])

### Inverse

In [37]:
Vs = V[[0, 1, 2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [38]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [39]:
Vs_inv.dot(Vs) # equal to Identity Matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])